version: '3'

# ------------------------------------------------------------------------------
# These images must be built in advance, or docker-compose will build them.
# cd ~/dockerfiles/database/ol7_183
# docker build -t ol7_183:latest .
# 
# cd ~/dockerfiles/ords/ol7_ords
# docker build -t ol7_ords:latest .
#
# Run it.
# cd ~/dockerfiles/compose/ol7_183_ords
# docker-compose up
# ------------------------------------------------------------------------------

services:
  # ORDS service
  ordsservice:
    build:
      context: ../../ords/ol7_ords/
      dockerfile: Dockerfile
    depends_on:
      - dbservice
    image: ol7_ords:latest
    # Comment out volume if you don't care about a persistent CATALINA_BASE.
    volumes:
      - /home/docker_user/volumes/ol7_183_ords_tomcat:/u01/config/instance1
    environment:
      - DB_HOSTNAME=dbservice
      - DB_PORT=1521
      - DB_SERVICE=pdb1
      - APEX_PUBLIC_USER_PASSWORD=ApexPassword1
      - APEX_TABLESPACE=APEX
      - TEMP_TABLESPACE=TEMP
      - APEX_LISTENER_PASSWORD=ApexPassword1
      - APEX_REST_PASSWORD=ApexPassword1
      - PUBLIC_PASSWORD=ApexPassword1
      - SYS_PASSWORD=SysPassword1
      - KEYSTORE_PASSWORD=KeystorePassword1
    ports:
      - "8080:8080"
      - "8443:8443"

  # Oracle Database service
  dbservice:
    build:
      context: ../../database/ol7_183/
      dockerfile: Dockerfile
    image: ol7_183:latest
    # Use persistent volume of your choice.
    volumes:
      #- db-data:/u02
      - /home/docker_user/volumes/ol7_183_ords_db:/u02
    environment:
      - SYS_PASSWORD=SysPassword1
      - PDB_PASSWORD=PdbPassword1
      - APEX_EMAIL=me@example.com
      - APEX_PASSWORD=ApexPassword1
    ports:
      - "1521:1521"

#volumes:
#  db-data:
  
